# Generated by Django 3.0 on 2019-12-20 01:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('levels', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('date_listed', models.DateField(default=datetime.date(2019, 12, 20))),
                ('status', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.IntegerField()),
                ('min_baths', models.IntegerField()),
                ('max_baths', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('min_sqft', models.IntegerField()),
                ('max_sqft', models.IntegerField()),
                ('levels', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('school_rating', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_fav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_agent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
