# Generated by Django 3.0 on 2019-12-20 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='user_fav',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_fav',
            name='user_fav',
        ),
        migrations.DeleteModel(
            name='User_pref',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='User_fav',
        ),
    ]
