# Generated by Django 3.0 on 2019-12-20 04:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20191220_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('levels', models.IntegerField()),
                ('date_listed', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=100)),
                ('listing_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
