# Generated by Django 3.0 on 2019-12-29 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191228_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Property')),
            ],
        ),
    ]
